
package vistas;

import Entidades.Caja;
import Entidades.Paciente;
import Entidades.Protocolo;
import Entidades.tipoProtocolo;
import Metodos.cajaData;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class Cajas extends javax.swing.JFrame {

   private cajaData cData;
    public Cajas() {
        initComponents();
          cData = new cajaData();
          
           DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Atiende");
    model.addColumn("Costo");
    model.addColumn("Forma de pago");
    model.addColumn("Protocolo");
    model.addColumn("Fecha");
    model.addColumn("Efectivo");
     model.addColumn("Transf");
     model.addColumn("CueCorri");
      model.addColumn("Obra Social");
    

    // Asignar el modelo a la tabla existente (tableInformes)
    tableInforme.setModel(model);

    // Ajustar el ancho de las columnas en tableInformes
    TableColumnModel columnModel = tableInforme.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(30);  // ID
    columnModel.getColumn(1).setPreferredWidth(70); // Paciente
    columnModel.getColumn(2).setPreferredWidth(90); // Protocolo
    columnModel.getColumn(3).setPreferredWidth(70); // Fecha Solicitud
    columnModel.getColumn(4).setPreferredWidth(100); // Fecha Entrega
    columnModel.getColumn(5).setPreferredWidth(100);  // Monto
    columnModel.getColumn(6).setPreferredWidth(80); // Estado
    columnModel.getColumn(7).setPreferredWidth(80); // Fecha Entrega
    columnModel.getColumn(8).setPreferredWidth(80); // Fecha Entrega
    columnModel.getColumn(9).setPreferredWidth(80); // Fecha Entrega
  
    
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarActionPerformed(evt);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxFormaPago = new javax.swing.JComboBox<>();
        dcDesde = new com.toedter.calendar.JDateChooser();
        dcHasta = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInforme = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtOS = new javax.swing.JTextField();
        txtCC = new javax.swing.JTextField();
        txtTransferencia = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Cuenta Corriente", "Transferencia" }));
        jPanel1.add(cbxFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, 40));
        jPanel1.add(dcDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 200, 40));
        jPanel1.add(dcHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 200, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos-micro/lupa (1).png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 120, 40));

        jLabel2.setText("Forma de Pago");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setText("Desde");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel4.setText("Hasta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        tableInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableInforme);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 800, 220));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos-azules/30/adelante.png"))); // NOI18N
        jButton1.setText("  SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 120, 40));

        txtOS.setBorder(null);
        jPanel1.add(txtOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 70, -1));

        txtCC.setBorder(null);
        jPanel1.add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 70, -1));

        txtTransferencia.setBorder(null);
        jPanel1.add(txtTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 480, 70, -1));

        txtEfectivo.setBorder(null);
        jPanel1.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 70, -1));

        txtTotal.setBorder(null);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Tipos de Caja");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondos/marquesina-1_B.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       try {
        // Obtener la forma de pago seleccionada
        String formaPagoSeleccionada = (String) cbxFormaPago.getSelectedItem();

        // Obtener las fechas desde los DateChooser
        Date fechaDesde = dcDesde.getDate();
        Date fechaHasta = dcHasta.getDate();

        // Validar que las fechas no sean nulas
        if (fechaDesde == null || fechaHasta == null) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione las fechas", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Variables para almacenar los resultados
        List<Caja> resultados = new ArrayList<>();

        // Buscar los registros de caja según la forma de pago y fechas
        resultados = cData.buscarPorFormaDePagoYFechas(formaPagoSeleccionada, fechaDesde, fechaHasta);

        // Limpiar la tabla antes de agregar los nuevos resultados
        DefaultTableModel model = (DefaultTableModel) tableInforme.getModel();
        model.setRowCount(0);

        // Agregar los datos a la tabla
        for (Caja caja : resultados) {
            model.addRow(new Object[]{
                caja.getIdCaja(),
                caja.getUsuario(),
                caja.getMonto(),
                caja.getForma_de_pago(),
                caja.getNumero_protocolo(),
                caja.getFecha(),
                caja.getEfectivo(),
                caja.getTransferencia(),
                caja.getCuenta_corriente(),
                caja.getObra_social()
            });
        }
          // Sumar los montos y mostrar en txtResultado
        double totalMonto = 0;
         double totalEfe = 0;
          double totalTran = 0;
           double totalCC = 0;
            double totalOS = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            totalMonto += (double) model.getValueAt(i, 2); // Suma los valores de la columna "Monto"
             totalEfe += (double) model.getValueAt(i, 6);
             totalTran += (double) model.getValueAt(i, 7);
             totalCC += (double) model.getValueAt(i, 8);
             totalOS += (double) model.getValueAt(i, 9);
        }
        txtTotal.setText(String.valueOf(totalMonto));
        txtEfectivo.setText(String.valueOf(totalEfe));
        txtTransferencia.setText(String.valueOf(totalTran));
        txtCC.setText(String.valueOf(totalCC));
        txtOS.setText(String.valueOf(totalOS));
        
        

        // Mostrar mensaje si no hay resultados
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados para la búsqueda.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbxFormaPago;
    private com.toedter.calendar.JDateChooser dcDesde;
    private com.toedter.calendar.JDateChooser dcHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableInforme;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtOS;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTransferencia;
    // End of variables declaration//GEN-END:variables
}
